server:
  port: 8481
spring:
  application:
    name: service-hello
  rabbitmq:
    host: 192.168.41.16
    port: 5672
    username: guest
    password: guest
  zipkin:
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      #采样率，推荐0.1，百分之百收集的话存储可能扛不住
      probability: 1.0 #Sleuth 默认采样算法的实现是 Reservoir sampling，具体的实现类是 PercentageBasedSampler，默认的采样比例为: 0.1，即 10%。我们可以通过 spring.sleuth.sampler.probability 来设置，所设置的值介于 0 到 1 之间，1 则表示全部采集